# Generated by Django 2.2.12 on 2020-05-23 15:46

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=django_bleach.models.BleachField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_bleach.models.BleachField(),
        ),
    ]
