# Generated by Django 2.2.12 on 2020-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed_type', models.CharField(max_length=200)),
                ('more_detail', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
