# Generated by Django 2.2.12 on 2020-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical', models.BooleanField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
