# Generated by Django 2.2.12 on 2020-05-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
