# Generated by Django 2.2.12 on 2020-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200523_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(max_length=200)),
                ('more_detail', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
