# Generated by Django 2.2.12 on 2020-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
